#!/usr/bin/python
"""
    Blank web page generated by python. This script should be copied and renamed
"""
import time
html_file = open('/var/www/html/scripts/blank_page.html', mode="w")

new_page = ("<!DOCTYPE html>\n\
<html lang=\"en\">\n\
<head>\n\
<title>Ohashisan</title>\n\
<style>\n\
table, th, td {\n\
  border: 0px solid black;\n\
  border-collapse: collapse;\n\
}\n\
\n\
th, td {\n\
  padding: 5px;\n\
}\n\
\n\
table.center {\n\
  margin-left: auto;\n\
  margin-right: auto;\n\
}\n\
</style>\n\
</head>\n\
<body>\n\
<center>\n\
<table width=\"800\">\n\
    <tr>\n\
        <td align=\"center\">\n\
            <hr width=\"800\">\n\
            <h3><b>Ohashisan (AKA reddirt.lab)</b></h3>\n\
                <a href=\"/\">Home</a> |\n\
                <a href=\"/bloghts/\">Bloghts</a> |\n\
                <a href=\"/certs/\">Certs</a> |\n\
                <a href=\"/commo/\">Commo</a> |\n\
                <a href=\"/google/\">Google Dorking</a> |\n\
                <a href=\"/scripts/\">Scripts</a> |\n\
                <a href=\"/tech/\">Tech</a> |\n\
                <a href=\"http://t7mdxxegiaz3jxbk3n6j44eujasg2pjydfqoivm7ekwvcrouje3jucid.onion/thedarkside.html\">The Dark Side</a>\n\
                <hr width=\"800\">\n\
        </td>\n\
    </tr>\n\
</table>\n\
<p>\n\
<table width=\"800\">\n\
    <tr>\n\
        <td valign=\"top\" width=\"100\" colspan=\"1\">\n\
            <a href=\"/pics/ohashi.jpg\"><img src=\"/pics/ohashi.jpg\" width=\"100%\"></a>\n\
        </td>\n\
        <td valign=\"top\" colspan=\"2\">\n\
            Left blank intentionally.\n\
        </td>\n\
    </tr>\n\
    <tr>\n\
        <td valign=\"top\" align=\"center\" width=\"100\" colspan=\"1\">\n\
            <img src=\"/pics/me_and_pezz_round.jpg\" width=\"100%\"><br>\n\
                Road Dog Pebbs\n\
        </td>\n\
        <td colspan=\"1\">\n\
            Left blank intentionally.\n\
            <p>\n\
        </td>\n\
    </tr>\n\
</table>\n\
</center>\n\
</body>\n\
</html>\n\
")

html_file.write(new_page)
html_file.close()

#print(new_page)

